// export const students = [
//     { name: "Arijit Barik", age: 22, grade: "A" },
//     { name: "Rahul Sharma", age: 24, grade: "B" },
//     { name: "Ankit Verma", age: 27, grade: "C" },
//     { name: "Sourav Das", age: 23, grade: "B" },
//     { name: "Rohan Gupta", age: 29, grade: "A" },
//     { name: "Vikram Singh", age: 26, grade: "D" },
//     { name: "Aman Yadav", age: 25, grade: "C" },
//     { name: "Kunal Roy", age: 28, grade: "B" },
//     { name: "Abhishek Paul", age: 30, grade: "A" },
//     { name: "Priyanshu Nair", age: 22, grade: "D" },
//     { name: "Sanjay Kumar", age: 24, grade: "B" },
//     { name: "Nikhil Jain", age: 27, grade: "C" },
//     { name: "Harsh Patel", age: 23, grade: "A" },
//     { name: "Deepak Mishra", age: 29, grade: "B" },
//     { name: "Manish Tiwari", age: 26, grade: "D" },
//     { name: "Aditya Sen", age: 25, grade: "C" },
//     { name: "Ritesh Pandey", age: 28, grade: "A" },
//     { name: "Sumit Chatterjee", age: 30, grade: "B" },
//     { name: "Gaurav Mehta", age: 22, grade: "C" },
//     { name: "Ashish Thakur", age: 24, grade: "D" },
//     { name: "Tarun Malhotra", age: 27, grade: "A" },
//     { name: "Neeraj Saxena", age: 23, grade: "B" },
//     { name: "Ravi Kapoor", age: 29, grade: "C" },
//     { name: "Varun Bansal", age: 26, grade: "D" },
//     { name: "Shubham Ghosh", age: 25, grade: "A" },
//     { name: "Lokesh Reddy", age: 28, grade: "B" },
//     { name: "Yash Agarwal", age: 30, grade: "C" },
//     { name: "Pankaj Sinha", age: 22, grade: "D" },
//     { name: "Hemant Joshi", age: 24, grade: "A" },
//     { name: "Mohit Arora", age: 27, grade: "B" },
//     { name: "Anurag Kulkarni", age: 23, grade: "C" },
//     { name: "Prateek Dubey", age: 29, grade: "D" },
//     { name: "Siddharth Rao", age: 26, grade: "A" },
//     { name: "Mayank Tripathi", age: 25, grade: "B" },
//     { name: "Arjun Bhattacharya", age: 28, grade: "C" },
//     { name: "Tushar Bhardwaj", age: 30, grade: "D" },
//     { name: "Rajesh Iyer", age: 22, grade: "A" },
//     { name: "Akash Dutta", age: 24, grade: "B" },
//     { name: "Kartik Pillai", age: 27, grade: "C" },
//     { name: "Shivam Chauhan", age: 23, grade: "D" },
//     { name: "Naveen Menon", age: 29, grade: "A" },
//     { name: "Devansh Shetty", age: 26, grade: "B" },
//     { name: "Chirag Desai", age: 25, grade: "C" },
//     { name: "Aayush Khanna", age: 28, grade: "D" },
//     { name: "Rajat Bhatia", age: 30, grade: "A" },
//     { name: "Saket Srivastava", age: 22, grade: "B" },
//     { name: "Pranav Kulshrestha", age: 24, grade: "C" },
//     { name: "Ujjwal Prasad", age: 27, grade: "D" },
//     { name: "Dhruv Anand", age: 23, grade: "A" },
//     { name: "Ishan Mukherjee", age: 29, grade: "B" }
// ];


export const students = [
  { name: "Arijit Barik", age: 22, grade: "A", department: "CSE", city: "Kolkata", gender: "Male", year: 4, isScholarship: true },
  { name: "Rahul Sharma", age: 24, grade: "B", department: "ECE", city: "Delhi", gender: "Male", year: 3, isScholarship: false },
  { name: "Ankit Verma", age: 27, grade: "C", department: "ME", city: "Mumbai", gender: "Male", year: 2, isScholarship: false },
  { name: "Sourav Das", age: 23, grade: "B", department: "CSE", city: "Kolkata", gender: "Male", year: 3, isScholarship: true },
  { name: "Rohan Gupta", age: 29, grade: "A", department: "CE", city: "Delhi", gender: "Male", year: 4, isScholarship: false },
  { name: "Vikram Singh", age: 26, grade: "D", department: "ME", city: "Mumbai", gender: "Male", year: 2, isScholarship: false },
  { name: "Aman Yadav", age: 25, grade: "C", department: "ECE", city: "Bangalore", gender: "Male", year: 3, isScholarship: true },
  { name: "Kunal Roy", age: 28, grade: "B", department: "CSE", city: "Kolkata", gender: "Male", year: 4, isScholarship: false },
  { name: "Abhishek Paul", age: 30, grade: "A", department: "CE", city: "Delhi", gender: "Male", year: 4, isScholarship: true },
  { name: "Priyanshu Nair", age: 22, grade: "D", department: "ECE", city: "Bangalore", gender: "Male", year: 1, isScholarship: false },
  { name: "Sanjay Kumar", age: 24, grade: "B", department: "ME", city: "Mumbai", gender: "Male", year: 3, isScholarship: false },
  { name: "Nikhil Jain", age: 27, grade: "C", department: "CSE", city: "Kolkata", gender: "Male", year: 2, isScholarship: true },
  { name: "Harsh Patel", age: 23, grade: "A", department: "CE", city: "Delhi", gender: "Male", year: 3, isScholarship: false },
  { name: "Deepak Mishra", age: 29, grade: "B", department: "ME", city: "Mumbai", gender: "Male", year: 4, isScholarship: false },
  { name: "Manish Tiwari", age: 26, grade: "D", department: "ECE", city: "Bangalore", gender: "Male", year: 2, isScholarship: true },
  { name: "Aditya Sen", age: 25, grade: "C", department: "CSE", city: "Kolkata", gender: "Male", year: 3, isScholarship: false },
  { name: "Ritesh Pandey", age: 28, grade: "A", department: "CE", city: "Delhi", gender: "Male", year: 4, isScholarship: true },
  { name: "Sumit Chatterjee", age: 30, grade: "B", department: "ME", city: "Mumbai", gender: "Male", year: 4, isScholarship: false },
  { name: "Gaurav Mehta", age: 22, grade: "C", department: "ECE", city: "Bangalore", gender: "Male", year: 1, isScholarship: false },
  { name: "Ashish Thakur", age: 24, grade: "D", department: "CSE", city: "Kolkata", gender: "Male", year: 2, isScholarship: true }
];
